### ISSUE TITLE
Make a print class for bootSVD object

### ISSUE THREAD

**Issue by muschellij2** [aaronjfisher/bootSVD#1]
If you call 
svdX <- fastSVD(X)
then 
svdX
may be good to have it not spit out everything.   If not print default, then a summary default - see stats:::summary.prcomp for what I mean.

**Comment by aaronjfisher** [comment]
Hi John, it's been an embarrassingly long time now that I didn't see this, but I've finally added print methods for fastSVD output and bootSVD output

**Comment by muschellij2** [comment]
Awesome - looks great.  Hope all is well!
Best,
John
